Fix: Staging release concurrency
When applying too many changes at once to the main branch, worflows may fail
due to concurrency when building the staging environment.

```
git push gh HEAD:staging
To https://github.com/Teamwork/mcp.git
 ! [rejected]        HEAD -> staging (fetch first)
error: failed to push some refs to 'https://github.com/Teamwork/mcp.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
make: *** [Makefile:49: git-push] Error 1
```

Adding a configuration to cancel workflows and only keep the latest (most
recent one) running.