Fix: Add missing `git` tool in the image build
`golang:1.26-alpine` doesn't contain the `git` tool anymore.

```
go: github.com/teamwork/twapi-go-sdk@v1.13.4: unable to resolve git version: failed to execute git version: exec: "git": executable file not found in $PATH
ERROR: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```